### ISSUE TITLE
Can I apply FRePo to a regression task?

### ISSUE THREAD

**Issue by WXL520** [yongchao97/FRePo#10]
Dear YongChao,

Can I apply FRePo to Multivariable time series forecasting tasks? 

I tried and failed, I got huge meta-loss like 10^10 (I keep dimension > number of samples, so that's not the reason).

The shape of my feature map here is (batch_size, num_nodes, seq_len, dim), so the shape of feat_tar is (1024x170x1, 512), and the shape of feat_syn is (10x170x1, 512), which is much larger than that in image classification. Do you think this is the reason?

Looking forward to your reply!

**Comment by yongchao97** [comment]
Hi,

From your description, do you want to distill a set containing 10 examples form 1024 examples? 

FRePo may not give very strong performance when the feature dimension is as large as 170x512. Honestly, I do not have a good intuition on time series data. But the meta loss 10^10 suggests that there is something fundamentally wrong. I suggest to play around with the hyperparameter and architecture to see whether you can get a reasonable meta-loss.

**Comment by WXL520** [comment]
Hi Yongchao,

Thank you for your reply!
I applied FRePo to a time series classification task and achieved good results, increasing the accuracy from 0.39 (subset) to 0.63 (syn data).
However, when I applied FRePo to a time series regression task, the improvement was marginal, with mae reduced from 63 (subset) to 58 (syn data).
Do you think the reason for the different performance is that FRePo is tailored for classification tasks and we need to make some changes to achieve good performance on regression tasks, or dataset distillation is simply not suitable for regression tasks?
