### ISSUE TITLE
Suggestions for measuring FLOPs

### ISSUE THREAD

**Issue by RK-TUI** [yongchao97/FRePo#11]
I want to measure the FLOPs required for the Distillation process. Do you have any suggestions on how to do it in your JAX implementation?

**Comment by yongchao97** [comment]
The most accurate one may be computing it by hand. You calculate the Flops per gradient update and then multiply by the number of training steps. Or you can measure some empirical statistics using some toolkit (https://docs.nvidia.com/deeplearning/frameworks/dlprof-user-guide/), but I have not used that before. So, I cannot comment on how accurate it is.
