### ISSUE TITLE
A problem of environment 

### ISSUE THREAD

**Issue by RealAidanJoe** [yongchao97/FRePo#9]
I followed how to set up the environment on your README.md, but it seems to have some problems, could you help me to fix it?
I want to evaluate the checkpoints you provide, but I'm unfamiliar with JAX
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/71580066/223313916-424698a1-4beb-4f10-84b0-d73fb7e38760.png">

I successfully create the environment from environment.yaml using conda, and the environment variables are set as follows:
```
# Configure Environment Variable (Change to your own path)

export LD_LIBRARY_PATH=/home/name/anaconda3/envs/frepo/lib:$LD_LIBRARY_PATH
export XLA_FLAGS=--xla_gpu_cuda_data_dir=/home/name/anaconda3/envs/frepo
export PATH=/home/name/anaconda3/envs/frepo:$PATH
```

**Comment by RealAidanJoe** [comment]
Hi,
Here are the versions of Jax, Jaxlib, and Tensorflow I got using `conda list`:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/71580066/223612082-1ea5a91d-fe27-467c-9251-0ec91716055a.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/71580066/223612139-729b1e39-eddb-4877-9b8d-0deea503080b.png">

And I also verified the Jax installation, the jax.devices() is true, but I failed to do some matrix multiplication because the same error:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/71580066/223611619-0ae19ae9-e60d-4388-ae57-b94016303e8b.png">
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/71580066/223613231-6155f291-56a6-43be-9094-2f6bf938109e.png">

**Comment by yongchao97** [comment]
I guess it might be the Jax version problem that causes some breaking changes. Could you try the following setup?

jax 0.3.21
jaxlib 0.3.20+cuda11.cudnn82
tensorflow 2.10.0
tensorflow-datasets 4.7.0
